config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: "products#index"

  resources :products do
    collection do
      get 'purchase_details_confirmation'
      get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
    end
    
  end
  resources :users, only: [:show, :destroy]

  resources :credit_cards, only: [:new, :create, :show, :destroy] do
  end
  resources :products do
    # 他の記述は省略
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  

end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  validates :customer_id,:card_id,:user_id, presence: true
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

    require "payjp" #PAYJPとやり取りするために、payjpをロード

    def new
      # 前回のnewアクションに追記
      # すでにクレジットカード登録されている場合は、showアクションにリダイレクト
      if CreditCard.where(user_id: current_user.id).exists?
        redirect_to credit_card_path(current_user.id)
      else
        @card = CreditCard.new
      end
    end

    def create
      # 前回credentials.yml.encに記載したAPI秘密鍵を呼び出します。
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]

      # 後ほどトークン作成処理を行いますが、そちらの完了の有無でフラッシュメッセージを表示させます。
      if params["payjp_token"].blank?
        redirect_to action: "new", alert: "クレジットカードを登録できませんでした。"
      else
      # 無事トークン作成された場合のアクション(こっちが本命のアクション)
      # まずは生成したトークンから、顧客情報と紐付け、PAY.JP管理サイトに登録
        customer = Payjp::Customer.create(
          email: current_user.email,
          card: params["payjp_token"],
          metadata: {user_id: current_user.id} #最悪なくてもOK！
        )
        # 今度はトークン化した情報を自アプリのCredit_cardsテーブルに登録！
        @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
        # 無事、トークン作成とともにcredit_cardsテーブルに登録された場合、createビューが表示されるように条件分岐
        if @card.save
          #もしcreateビューを作成しない場合はredirect_toなどで表示ビューを指定
        else
          redirect_to action: "create"
        end
        redirect_to user_path(current_user.id)
      end
    end
    def show
      # ログイン中のユーザーのクレジットカード登録の有無を判断
      @card = CreditCard.find_by(user_id: current_user.id)
      if @card.blank?
        # 未登録なら新規登録画面に
        redirect_to action: "new"
      else
        # 前前回credentials.yml.encに記載したAPI秘密鍵を呼び出します。
        Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
        # ログインユーザーのクレジットカード情報からPay.jpに登録されているカスタマー情報を引き出す
        customer = Payjp::Customer.retrieve(@card.customer_id)
        # カスタマー情報からカードの情報を引き出す
        @customer_card = customer.cards.retrieve(@card.card_id)

        ##カードのアイコン表示のための定義づけ
        @card_brand = @customer_card.brand
        case @card_brand
        when "Visa"
          # 例えば、Pay.jpからとってきたカード情報の、ブランドが"Visa"だった場合は返り値として
          # (画像として登録されている)Visa.pngを返す
          @card_src = "visa.png"
        when "JCB"
          @card_src = "jcb.png"
        when "MasterCard"
          @card_src = "master.png"
        when "American Express"
          @card_src = "amex.png"
        when "Diners Club"
          @card_src = "diners.png"
        when "Discover"
          @card_src = "discover.png"
        end

        #  viewの記述を簡略化
        ## 有効期限'月'を定義
        @exp_month = @customer_card.exp_month.to_s
        ## 有効期限'年'を定義
        @exp_year = @customer_card.exp_year.to_s.slice(2,3)
      end
    end

    def destroy
      # ログイン中のユーザーのクレジットカード登録の有無を判断
      @card = CreditCard.find_by(user_id: current_user.id)
      if @card.blank?
        # 未登録なら新規登録画面に
        redirect_to action: "new"
      else
        # 前前回credentials.yml.encに記載したAPI秘密鍵を呼び出します。
        Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
        # ログインユーザーのクレジットカード情報からPay.jpに登録されているカスタマー情報を引き出す
        customer = Payjp::Customer.retrieve(@card.customer_id)
        # そのカスタマー情報を消す
        customer.delete
        @card.delete
        # 削除が完了しているか判断
        if @card.destroy
        # 削除完了していればdestroyのビューに移行
        # destroyビューを作るのが面倒であれば、flashメッセージを入れてトップページやマイページに飛ばしてもOK

        else
          # 削除されなかった場合flashメッセージを表示させて、showのビューに移行
          redirect_to credit_card_path(current_user.id), alert: "削除できませんでした。"
        end
      end
      redirect_to user_path(current_user.id)
    end

end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/create.html.haml
.create
  .create__frame
    .create__frame__message
      登録が完了しました。
    %ul.create__frame__btns
      -# マイページに戻るパスを指定
      %li.my_page_link
        = link_to "マイページに戻る", user_path(current_user.id), class: "my_page_link__btn"
      -# のちに実装する、登録クレジットカード詳細表示(showアクション)に行くパスを指定
      %li.credit_cards_index_link
        = link_to "登録カード一覧", credit_cards_path(current_user.id), class: "credit_cards_index_link__btn"

app/views/credit_cards/destroy.html.haml
.destoroy
  .destoroy__frame
    .destoroy__frame__message
      削除が完了しました。
    %ul.destoroy__frame__btns
      %li.credit_card_new_link
        = link_to "クレジットカード新規登録", new_credit_card_path, class: "credit_card_new_link__btn"
      %li.my_page_link
        = link_to "マイページに戻る", user_path(current_user.id), class: "my_page_link__btn"

app/views/credit_cards/new.html.haml
= render "/application/header"

.wrapper
  .main
    .card_add 
      .title クレジットカード情報入力

      -#form_tagメソッドでcreateアクションに入力情報を渡します。
      = form_tag(credit_cards_path, method: :post, id: "charge-form", class: "details", name: "inputForm") do
        .number-details
          .card-num カード番号
          %span.must_check 必須
        .number
          = text_field_tag 'payment_card_no', "", class: 'cardnumber', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
        -# 事前にassets/imagesにcardsファイルを作成、中に各カード会社の画像を入れておき、呼び出す。
        

        .expirationdate
          .expirationdate__details
            .date 有効期限
            %span.must_check 必須
          .expirationdate__choice
            .month
              %select#payment_card_month.card-default{name: "payment_card_month", type: "text"}
                %option{value: "1"} 01
                %option{value: "2"} 02
                %option{value: "3"} 03
                %option{value: "4"} 04
                %option{value: "5"} 05
                %option{value: "6"} 06
                %option{value: "7"} 07
                %option{value: "8"} 08
                %option{value: "9"} 09
                %option{value: "10"} 10
                %option{value: "11"} 11
                %option{value: "12"} 12
              .month-details 月
            .year
              %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
                %option{value: "2020"} 20
                %option{value: "2021"} 21
                %option{value: "2022"} 22
                %option{value: "2023"} 23
                %option{value: "2024"} 24
                %option{value: "2025"} 25
                %option{value: "2026"} 26
                %option{value: "2027"} 27
                %option{value: "2028"} 28
                %option{value: "2029"} 29
                %option{value: "2030"} 30
              .year-details 年

        .securitycode
          .securitycode__details
            .securitycode__details__title セキュリティコード
            %span.must_check 必須
          .securitycode__cardsecurity
            = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
          .card-question カード裏面の番号とは？
        .add 
          = submit_tag "登録する", class: "add__btn", id: "payment_card_submit-button"
= render "/application/banner"
= render "/application/footer"

app/views/credit_cards/show.html.haml
= render "/application/header"
.main
  .show
    .show__frame
      .show__frame__title
        登録クレジットカード情報
      .credit_card__list
        .credit_card__list__title
          クレジットカード一覧
        .credit_card__list__frame
          .credit_card_info
            .credit_card_info__brand
              -# # showメソッドで定義した@card_srcを呼び出し
              -# # 画像をcardsというフォルダを作り、入れておく
              = image_tag "cards/#{@card_src}", class: "credit_card_info__brand__img", alt: @card_brand
            .credit_card_info__numbers
              .number
                -# # Pay.jpから取得したカード番号の末尾４桁を取得
                = "**** **** **** " + @customer_card.last4
              .expiration_date
                .expiration_date__title
                  有効期限
                .expiration_date__info
                  -# # showメソッドで定義した有効期限の年と月を取得
                  = @exp_month + " / " + @exp_year
          .destroy__function
            .destroy__function__link
              -# # 削除ボタンを作成、押すとdestroyメソッドが働くように
              = link_to credit_card_path, method: :delete, class: "add__btn" do
                削除する
= render "/application/banner"
= render "/application/footer"