config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: "products#index"

  resources :products do
    collection do
      get 'purchase_details_confirmation'
      get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
    end
    
  end
  resources :users, only: [:show, :destroy]

  resources :credit_cards, only: [:new, :create, :show, :destroy] do
  end
  resources :products do
    # 他の記述は省略
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:first_name,:first_name_furigana,:last_name,:last_name_furigana,:birthday,:postal_code,:city,:building_name,:tel_number,:other,:city,:postal_code,:building_name,:prefecture_id])
  end

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_banner.html.haml
.top-banner
  .top-banner__body
    %h2.top-banner__body__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.top-banner__body__text
      今すぐ無料ダウンロード!
    .top-banner__body__icon
      = link_to image_tag ("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg"), class:"badge"
      = link_to image_tag ("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg"), class:"badge"

app/views/application/_footer.html.haml
.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li= link_to '会社概要(運営会社)', '#', class: "footer-link"
        %li= link_to 'プライバシーポリシー', '#', class: "footer-link"
        %li= link_to 'FURIMA利用規約','#', class: "footer-link"
        %li= link_to 'ポイントに関する特約', '#', class: "footer-link"
    %li.content
      %h2.content_head FURIMAを見る
      %ul
        %li= link_to 'カテゴリー一覧', '#', class: "footer-link"
        %li= link_to 'ブランド一覧', '#', class: "footer-link"
    %li.content
      %h2.content_head ヘルプ&ガイド
      %ul
        %li= link_to 'FURIMAガイド', '#', class: "footer-link"
        %li= link_to 'FURIMAロゴ利用ガイドライン', '#', class: "footer-link"
        %li= link_to 'お知らせ', '#', class: "footer-link"
  .footer__logo
    = link_to image_tag "material/logo/logo-white.png", class:"footer-logo"
    %p © FURIMA

app/views/application/_header.html.haml
%header.header
  .header__body
    .header__body__main
      .header__body__main__icon-space
        = link_to image_tag("material/logo/logo.png", class: "header__body__main__icon-space__icon"), root_path

      .header__body__main__searchbox
        %form.header__body__main__searchbox__form{"accept-charset" => "UTF-8", :action => "#", :method => "get"}
          %input{:name => "utf-8", :type => "hidden", :value => ""}/
          %input#searchInput.header__body__main__searchbox__form__input{:name => "key", :placeholder => "キーワードから探す"}/
          %label.header__body__main__searchbox__form__submit
            %button.header__body__main__searchbox__form__submit__button{:type => "submit"}
              = link_to image_tag "material/icon/icon-search 1.png", class:"header__body__main__searchbox__form__submit__button__image"
      %ul.header__body__main__resultslists

    .header__body__nav
      %ul.nav-left
        %li.nav-left__box.nav-left__box-category
          = link_to 'カテゴリー','#',class:"header__link"
        %li.nav-left__box
          = link_to 'ブランド','#',class:"header__link"
      %ul.nav-right
        -if user_signed_in?
          %li.nav-right__box.nav-right__box-login
            = link_to '商品出品',new_product_path, class:"header__link"
          %li.nav-right__box.nav-right__box-new
            = link_to 'マイページ',user_path(current_user.id),class:"header__link"
        -else
          %li.nav-right__box.nav-right__box-login
            = link_to 'ログイン',new_user_session_path,class:"header__link"
          %li.nav-right__box.nav-right__box-new
            = link_to '新規会員登録',new_user_registration_path,class:"header__link"