config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: "products#index"

  resources :products do
    collection do
      get 'purchase_details_confirmation'
      get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
    end
    
  end
  resources :users, only: [:show, :destroy]

  resources :credit_cards, only: [:new, :create, :show, :destroy] do
  end
  resources :products do
    # 他の記述は省略
    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  

end

app/models/product.rb
class Product < ApplicationRecord
  validates_associated :product_photos
  validates :name, presence: true, length: { maximum: 40 }
  validates :explanation, presence: true, length: { maximum: 1000 }
  validates :category_id, :status, :bear, :ship_day, presence: true
  validates :price,presence: true, inclusion: 300..9999999
  validates :product_photos, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :category
  has_many :product_photos, dependent: :destroy
  
  accepts_nested_attributes_for :product_photos, allow_destroy: true
  
  # validates :category_id, presence: ture 


  enum status: { 新品・未使用: 0, 未使用に近い: 1, 目立った傷や汚れなし: 2, やや傷や汚れあり: 3, 傷や汚れあり: 4, 全体的に状態が悪い: 5 }
  enum bear: { 送料込み（出品者負担）: 0, 着払い（購入者負担）: 1}
  enum ship_day: { １〜２日で発送: 0, ２〜３日で発送: 1, ４〜７日で発送: 2}
  enum shipping_method: { 未定: 0, クロネコヤマト: 1, ゆうパック: 2, ゆうメール: 3}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  def index
    
    @products = Product.all.includes(:product_photos).order(created_at: :desc)
    @parents = Category.where(ancestry: nil)
    
  end
  def show
    @parents = Category.where(ancestry: nil)
    @comments = Comment.where(product_id: params[:id])
    @user = User.find(@product.exhibitor_user_id)
    @product = Product.find(params[:id])
     
    
  end
  def new
    if user_signed_in?
      @product = Product.new
      @product.product_photos.build
      @category_parent_array = Category.where(ancestry: nil)
    else
      redirect_to root_path, notice: 'ログインもしくはサインインしてください。'
    end
  end
  def create
    @product = Product.new(product_params)
    if @product.save

      redirect_to root_path, notice: '出品完了'
    else
      @product = Product.new
      @product.product_photos.build
      flash.now[:alert] = '入力欄を再度ご確認ください。'
      render :new
      @category_parent_array = Category.where(ancestry: nil).pluck(:name).unshift("---")
    end
  end
  def edit
    @category_parent_array = Category.where(ancestry: nil)
    @grandchildren_category = @product.category
    @children_category = @grandchildren_category.parent

    @category_children_array = Category.where(ancestry: @children_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: @grandchildren_category.ancestry)
    @product.product_photos.build
  end
  def update
    @product.update(product_params)


    redirect_to product_path(params[:id])

  end
  def destroy
    @product = Product.find(params[:id])
    if current_user.id == @product.exhibitor_user_id && @product.destroy
      redirect_to root_path
    else
      @parents = Category.where(ancestry: nil)
      @comments = Comment.where(product_id: params[:id])
      render :show


    end
  end


  def get_category_children
    @category_children = Category.find_by(id: params[:parent_name], ancestry: nil).children
  end
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  private

  def product_params
    params.require(:product).permit(:name, :explanation, :category_id, :status, :bear, :shipping_method, :prefecture_id, :brand, :ship_day, :price, product_photos_attributes: [:photo, :id, :_destroy]).merge(exhibitor_user_id: current_user.id)
  end
  def set_product
    @product = Product.find(params[:id])
  end

  def ensure_currect_user
    if current_user.id != @product.exhibitor_user_id
      redirect_to root_path(params[:id])
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.haml
= render "/application/header"

-# アラート・ここから
.notifications
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)
-# アラート・ここまで


  - @product.product_photos.each do |photo|
    = image_tag photo.photo, class:'main-content__photoSub--small'

.new
  = form_for @product do |f|
    .product-photo
      %label 出品画像
      %span.require 必須
      %p 最大5枚までアップロードできます
      .product-photo__container
        .prev-content
          - @product.product_photos.each_with_index do |photo,i|
            - if photo.persisted?
              .preview-box{id:"preview-box__#{i}"}
                = image_tag photo.photo, class:'upper-box'
                .lower-box
                  .delete-box{id:"delete_btn_#{i}"}
                    %span 削除
        .label-content
          %label{for: "product_photos_attributes_#{@product.product_photos.length - 1}_product_photos", class: "label-box", id: "label-box--"}
            %pre.label-box__text-visible クリックしてファイルをアップロード
        .hidden-content
          = f.fields_for :product_photos do |i|
            = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy' if @product.product_photos[i.index].persisted?
            = i.file_field :photo, class: "hidden-field", id: "product_photos_attributes_#{i.index}_product_photos"
    .product
      %label  商品名
      %span.require 必須
      .product__name
        = f.text_field :name, placeholder: "40文字まで"
      %label 商品の説明
      %span.require 必須
      .product__explanation
        = f.text_area :explanation, placeholder: "商品の説明(必須 1000文字以内)\r\n(色、素材、重さ、定価、注意点など)\r\n\r\n例)2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでオススメです。"
    .product-details
      %p 商品詳細
      %label カテゴリー
      %span.require 必須
      .product-details__category
        = f.collection_select :category_id, Category.roots, :id, :name, {include_blank: "---",selected: @product.category&.root_id}, required: true,class:'category__select', id: 'parent_category'
        .category-wrapper-select#children_wrapper
          .category-wrapper-select__box
            = f.collection_select :category_id, @product.category.parent.siblings, :id, :name, {include_blank: "---",selected: @product.category.parent_id}, required: true,class:'category__select', id: 'child_category'
          .category-wrapper-select#grandchildren_wrapper
            .category-wrapper-select__box
              = f.collection_select :category_id, @product.category.siblings, :id, :name, {include_blank: "---",selected: @product.category.id}, required: true, class: 'category__select' ,id: 'grandchild_category'

      .product-details__brand
        %label ブランド
        %span.any 任意
        = f.text_field :brand, placeholder: "例）エルメス"
      %label 商品の状態
      %span.require 必須
      .product-details__status
        = f.select :status, Product.statuses.keys, id: "select_status"
    .delivery
      %p 配送について
      %label 配送料の負担
      %span.require 必須
      .delivery__charge
        = f.select :bear, Product.bears.keys
      %label 配送方法
      %span.any 任意
      .delivery__method
        = f.select :shipping_method, Product.shipping_methods.keys
      %label 発送元の地域
      %span.require 必須
      .delivery__prefecture
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name
      %label 発送までの日数
      %span.require 必須
      .delivery__send-day
        = f.select :ship_day, Product.ship_days.keys
    .selling__price
      %p 価格（¥300~9,999,999）
      %label 販売価格
      %span.require 必須
      %span ¥
      = f.number_field :price, placeholder: "0", id: "price-result"
    .exhibition-btn
      = f.submit '出品する', class:"submit-exhibit"
    .save-draft-btn
      = f.submit '下書きに保存'
    .return
      = link_to root_path do
        もどる
    .note
      禁止されている行為および出品物を必ずご確認ください。
      偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 
      また、出品をもちまして加盟店規約に同意したことになります。
  
  = render "/application/banner"
  = render "/application/footer"

app/views/products/index.html.haml
= render "/application/header"
.top-main
  %section.mainvisual
    .content
      %h2.content__title
        人生を変えるフリマアプリ
      %p.content__text
        FURIMAは誰でも簡単に出品・購入できる
        %br
          フリマアプリです
      .mainvisual__content__btn
        = link_to image_tag ("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg"), class:"badge"
        = link_to image_tag ("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg"), class:"badge"
  %section.mainintroduction
    %h2.subtitle
      FURIMAが選ばれる3つの理由
      .subtitle::after
    %ul.mainintroduction__lists
      %li.mainintroduction__lists__list
        .mainintroduction__lists__list__pict
          %span.mainintroduction__lists__list__pict__number
            1
          = image_tag "material/pict/pict-reason-01.jpg", class: "mainintroduction__lists__list__pict__image"
        %h3.mainintroduction__lists__list__text
          %span
            3分
          ですぐに出品
          %p.list__description
            スマホで入力するだけで簡単に出品できる！
        %li.mainintroduction__lists__list
          .mainintroduction__lists__list__pict
            %span.mainintroduction__lists__list__pict__number
              2
            = image_tag "material/pict/pict-reason-02.jpg", class: "mainintroduction__lists__list__pict__image"
          %h3.mainintroduction__lists__list__text
            %span
              シンプル
            で使いやすい
            %p.list__description
              めんどくさい入力は必要なく、検索も購入もスムーズ！
        %li.mainintroduction__lists__list
          .mainintroduction__lists__list__pict
            %span.mainintroduction__lists__list__pict__number
              3
            = image_tag "material/pict/pict-reason-03.jpg", class: "mainintroduction__lists__list__pict__image"
          %h3.mainintroduction__lists__list__text
            手数料
            %span
              業界最安
            %p.list__description
              最大3%で特に出品&購入
  %section.top-membership
    .top-membership__body
      %h2.top-membership__body__title
        会員数日本一位
      %p.top-membership__body__text
        FURIMAは、フリマアプリで最も人気
        %br
          出品・購入回数も業界最多です！
          %br
            ほしかったあの商品に出会えるかもしれません。
  %section.top-characteristic
    .top-characteristic__title
      FURIMAの特徴
    .top-characteristic__lists
      .top-characteristic__lists__list
        = image_tag "material/icon/icon-01.png", class: "top-characteristic__lists__list__picture"
        .top-characteristic__lists__list__title
          簡単に売り買いできる
        .top-characteristic__lists__list__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

      .top-characteristic__lists__list
        = image_tag "material/icon/icon-03.png", class: "top-characteristic__lists__list__picture"
        .top-characteristic__lists__list__title
          売上金は即日振込みに対応
        .top-characteristic__lists__list__text
          午前９時までに振込を依頼いただければ、翌日に指定の銀行に入金いたします！

      .top-characteristic__lists__list
        = image_tag "material/icon/icon-04.png", class: "top-characteristic__lists__list__picture"
        .top-characteristic__lists__list__title
          様々な支払いに対応
        .top-characteristic__lists__list__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.top-pickup
    %h2.top-pickup__title 
      ピックアップカテゴリー
      .top-pickup__subtitle
        新規投稿商品
      .product-box__lists
        - @products.each do |product|
          .product-box__list
            = link_to product_path(product.id) , class:'new-product' do
              %figure.product-box__img
                -if product.persisted?
                  = image_tag product.product_photos[0].photo, size: '220x150'
                  -if product.buyer_user_id.present? 
                    .items-box_photo__sold
                      .items-box_photo__sold__inner SOLD
              .product-box__body
                %h3.name 
                  = product.name
                .detail
                  %ul.price-line
                    %li.price 
                      = product.price
                      円
                    %li
                      %i.fa.fa-star.likeIcon
                      0
                  %p.tax （税込）
  %section.top-pickup
    %h2.top-pickup__title
      ピックアップブランド
    .top-pickup__subtitle
      アーカイバ

= render "/application/banner"
= render "/application/footer"

= link_to new_product_path , class: 'auction' do
  .auction-Btn
    %span.auction-Btn__text
      出品する
    =image_tag "material/icon/icon_camera.png",class:'auction-Btn__icon'

app/views/products/new.html.haml
= render "/application/header"

-# アラート・ここから
.notifications
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)
-# アラート・ここまで

.new
  = form_for @product do |f|
    .product-photo
      %label 出品画像
      %span.require 必須
      %p 最大5枚までアップロードできます
      .product-photo__container
        .prev-content
        .label-content
          %label{for: "product_photos_attributes_1_product_photos", class: "label-box", id: "label-box--1"}
            %pre.label-box__text-visible クリックしてファイルをアップロード
        .hidden-content
          = f.fields_for :product_photos do |i|
            = i.file_field :photo, class: "hidden-field"
            %input{class:"hidden-field", type: "file", name: "product[product_photos_attributes][1][photo]", id: "product_photos_attributes_1_product_photos" }
            %input{class:"hidden-field", type: "file", name: "product[product_photos_attributes][2][photo]", id: "product_photos_attributes_2_product_photos" }
            %input{class:"hidden-field", type: "file", name: "product[product_photos_attributes][3][photo]", id: "product_photos_attributes_3_product_photos" }
            %input{class:"hidden-field", type: "file", name: "product[product_photos_attributes][4][photo]", id: "product_photos_attributes_4_product_photos" }
            %input{class:"hidden-field", type: "file", name: "product[product_photos_attributes][5][photo]", id: "product_photos_attributes_5_product_photos" }
    .product
      %label  商品名
      %span.require 必須
      .product__name
        = f.text_field :name, placeholder: "40文字まで"
      %label 商品の説明
      %span.require 必須
      .product__explanation
        = f.text_area :explanation, placeholder: "商品の説明(必須 1000文字以内)\r\n(色、素材、重さ、定価、注意点など)\r\n\r\n例)2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでオススメです。"
    .product-details
      %p 商品詳細
      %label カテゴリー
      %span.require 必須
      .product-details__category
        = f.collection_select(:category_id, Category.roots,:id, :name,{include_blank:"---"}, {id: 'parent_category'})
      .product-details__brand
        %label ブランド
        %span.any 任意
        = f.text_field :brand, placeholder: "例）エルメス"
      %label 商品の状態
      %span.require 必須
      .product-details__status
        = f.select :status, Product.statuses.keys, id: "select_status"
    .delivery
      %p 配送について
      %label 配送料の負担
      %span.require 必須
      .delivery__charge
        = f.select :bear, Product.bears.keys
      %label 配送方法
      %span.any 任意
      .delivery__method
        = f.select :shipping_method, Product.shipping_methods.keys
      %label 発送元の地域
      %span.require 必須
      .delivery__prefecture
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name
      %label 発送までの日数
      %span.require 必須
      .delivery__send-day
        = f.select :ship_day, Product.ship_days.keys
    .selling__price
      %p 価格（¥300~9,999,999）
      %label 販売価格
      %span.require 必須
      %span ¥
      = f.number_field :price, placeholder: "0", id: "price-result"
    .exhibition-btn
      = f.submit '出品する', class:"submit-exhibit"
    .save-draft-btn
      = f.submit '下書きに保存'
    .return
      = link_to root_path do
        もどる
    .note
      禁止されている行為および出品物を必ずご確認ください。
      偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 
      また、出品をもちまして加盟店規約に同意したことになります。
  
  = render "/application/banner"
  = render "/application/footer"

app/views/products/show.html.haml
= render "/application/header"

.main
  .main-content
    %h1.item-name
      = @product.name
    .main-content__photo
      = image_tag @product.product_photos[0].photo, class:'item-main-content__photo--big'
      -if @product.buyer_user_id.present? 
        .items-box_photo__sold
          .items-box_photo__sold__inner SOLD

    .main-content__photoSub
      - @product.product_photos.each do |photo|
        = image_tag photo.photo, class:'main-content__photoSub--small'
    
    .main-content__price
      %p.lower-message__content
        = @product.price
        円
      %span.main-content__price--detail
        .main-content__price--detail-tax 
          (税込)
        .main-content__price--detail-shipFee 
          送料込み

    .main-content__purchase
      -if (user_signed_in? && @product.buyer_user_id == nil)
        -if (current_user.id == @product.exhibitor_user_id)
          %button.main-content__purchase--btn
            = link_to "商品情報を編集", edit_product_path(@product.id), id: "edit-btn"
          %button.main-content__purchase--btn
            = link_to "削除",product_path, method: :delete
        - else
          %button.main-content__purchase--btn
            = link_to "購入に進む" , buy_product_purchases_path(@product.id) , method: :get

    .main-content__description
      = @product.explanation
    
    %table.main-content__table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to @user.nickname, product_path, class: ""
            %div
        %tr
          %th カテゴリー
          %td
            = @product.category.parent.parent.name
            %br
              = @product.category.parent.name
              %br
                = @product.category.name
        %tr
          %th ブランド
          %td
            = @product.brand
        %tr
          %th 商品の状態
          %td 
            = @product.status
        %tr
          %th 配送料の負担
          %td 
            = @product.bear
        %tr
          %th 配送元地域
          %td 
            = @product.prefecture.name
        %tr
          %th 発送日の目安
          %td 
            = @product.ship_day 

    .main-content__btn
      %button.main-content__btn--like
        = icon('fas', 'star')
        お気に入り 
        .main-content__btn--like--numLike
        ０
      %button.main-content__btn--report
        = icon('fab', 'font-awesome-flag')
        不適切な商品の通報

  .comment
    - if @comments
      - @comments.each do |comment|
        .comment__history--name
          = icon('fas', 'user')
          = comment.user.nickname
        .comment__history--content
          = comment.text
          .comment__history--content-date
            Date:
            = comment.created_at

    %input.comment__input{id: "comment__input", name: "", type: "text", value: "", placeholder: ""}
    .comment__caution
      相手のことを考え丁寧なコメントを心がけましょう。
      %br
        不快な言葉遣いなどは利用制限や退会処分となることがあります。

    .comment__btn
      -if (user_signed_in?)
        -if (current_user.id?)
          %button.comment__btn--link{:name => "button", :type => "submit"}
            コメントする
            = icon('fas', 'comment')
        -else
          %button.comment__btn--link
            ログインしてください

  .other-products
    .other-products__links
      .other-products__links--privious
        = icon('fas', 'chevron-left')
        = link_to "前の商品","#{@product.id - 1}", method: :get

      .other-products__links--next
        = link_to "次の商品","#{@product.id + 1}", method: :get
        = icon('fas', 'chevron-right')


= render "/application/banner"
= render "/application/footer"

app/views/products/show.htnl.haml
.main
  .main-content
    %h1.item-name 
    .main-content__photo
      = image_tag "https://lh3.googleusercontent.com/proxy/3iYcqyqOKjg_Z_BqL8VP2EW7kc5P0p6X-fePvjibXvIyIhZxYRuUTwH9RghWP8xOEDiwxnPTyR1D3qGEReyI9n342JCQw1yHyo1QtKkIb5lEQvri"
    .main-content__photoSub
      = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png"
      = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png"
    .main-content__price
      %p.main-content__price--content
        90000円
      %span.main-content__price--detail
        .main-content__price--detail-tax 
          (税込)
        .main-content__price--detail-shipFee 
          送料込み

    .main-content__purchase
      %button.main-content__purchase--btn
        = link_to "編集、削除もしくは購入に進む" ,"#", id: "edit-btn"

    .main-content__description
      ここは商品の説明について
      記載しています。
    
    %table.main-content__table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to "ユーザーネーム", "path", class: ""
            %div
        %tr
          %th カテゴリー
          %td
            = link_to "カテゴリーネーム", "path", class: ""
            %br
              = link_to "カテゴリーネーム", "product_path", class: ""
              %br
                = link_to "カテゴリーネーム", "product_path", class: ""
        %tr
          %th ブランド
          %td
        %tr
          %th 商品の状態
          %td 
        %tr
          %th 配送料の負担
          %td 
        %tr
          %th 配送元地域
          %td 
        %tr
          %th 発送日の目安
          %td 

    .main-content__btn
      %button.main-content__btn--like
        = icon('fas', 'star')
        お気に入り 
        .main-content__btn--like--numLike
        ０
      %button.main-content__btn--report
        = icon('fab', 'font-awesome-flag')
        不適切な商品の通報

  .comment
    .comment__history
      .comment__history--content
      .comment__history--content-date
    %input.comment__input{id: "comment__input", name: "", type: "text", value: "", placeholder: ""}
    
    .comment__caution
      相手のことを考え丁寧なコメントを心がけましょう。
      %br
        不快な言葉遣いなどは利用制限や退会処分となることがあります。

    %button.comment__btn{:name => "button", :type => "submit"}
      = icon('fas', 'comment')
      コメントする

  .other-products
    .other-products__links
      .other-products__links--privious
        = icon('fas', 'chevron-left')
        = link_to "前の商品","#"

      .other-products__links--next
        = link_to "次の商品","#"
        = icon('fas', 'chevron-right')

    .other-products__genre
      = link_to "メンズをもっと見る", "/"